services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - news_network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rss_parser:
    build:
      context: .
      dockerfile: Dockerfile.parser
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - news_network
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    volumes:
      - ./static:/app/static
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - news_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  news_network:
    driver: bridge

volumes:
  mongodb_data:
